apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento-echo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magento-echo
  template:
    metadata:
      labels:
        app: magento-echo
    spec:
      containers:
      - name: magento-echo
        image: taufic/workshop:latest

---

apiVersion: v1
kind: Service
metadata:
  name: magento-echo-service
spec:
  selector:
    app: magento-echo
  ports:
    - port: 80
  type: ClusterIP
